package ru.gsw.way_to_success_ii.saveSystem

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity
data class User(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    @ColumnInfo(name = "max_health") val max_health: Int,
    @ColumnInfo(name = "health") val health: Int,
    @ColumnInfo(name = "max_mood") val max_mood: Int,
    @ColumnInfo(name = "mood") val mood: Int,
    @ColumnInfo(name = "max_satiety") val max_satiety: Int,
    @ColumnInfo(name = "satiety") val satiety: Int,
    @ColumnInfo(name = "first_name") val firstName: String,
    @ColumnInfo(name = "last_name") val lastName: String,
    @ColumnInfo(name = "age") val age: Int,
    @ColumnInfo(name = "days") val days: Int,
    @ColumnInfo(name = "year_days") val year_days: Int,
    @ColumnInfo(name = "rubles") val rubles: Long,
    @ColumnInfo(name = "dollars") val dollars: Long,
    @ColumnInfo(name = "respect") val respect: Long,
    @ColumnInfo(name = "sex") val sex: Int,
    @ColumnInfo(name = "gender") val gender: String,
    @ColumnInfo(name = "force") val force: Int,
    @ColumnInfo(name = "intelligence") val intelligence: Int,
    @ColumnInfo(name = "attractiveness") val attractiveness: Int,
    @ColumnInfo(name = "adaptability") val adaptability: Int,
    @ColumnInfo(name = "creativity") val creativity: Int,
    @ColumnInfo(name = "cheating") val cheating: Int,
    @ColumnInfo(name = "luck") val luck: Int,
    @ColumnInfo(name = "hard_work") val hard_work: Int,
    @ColumnInfo(name = "enterprise") val enterprise: Int
){
    constructor(
        max_health: Int,
        health: Int,
        max_mood: Int,
        mood: Int,
        max_satiety: Int,
        satiety: Int,
        firstName: String,
        lastName: String,
        age: Int,
        days: Int,
        year_days: Int,
        rubles: Long,
        dollars: Long,
        respect: Long,
        sex: Int,
        gender: String,
        force: Int,
        intelligence: Int,
        attractiveness: Int,
        adaptability: Int,
        creativity: Int,
        cheating: Int,
        luck: Int,
        hard_work: Int,
        enterprise: Int
    ) : this(
        0,
        max_health,
        health,
        max_mood,
        mood,
        max_satiety,
        satiety,
        firstName,
        lastName,
        age,
        days,
        year_days,
        respect,
        rubles,
        dollars,
        sex,
        gender,
        force,
        intelligence,
        attractiveness,
        adaptability,
        creativity,
        cheating,
        luck,
        hard_work,
        enterprise)
}